### ISSUE TITLE
Qual é o objetivo deste repositório?

### ISSUE THREAD

**Issue by alexandre-mbm** [magoolation/FreeVox#1]
Eu vi a descrição no cabeçalho do GitHub:

> Um repositório de aplicações com interfaces em audio para auxilio no dia-a-dia de pessoas com deficiencia idealizado e desenvolvido por membros da lista Cegos Programadores 

Mas, navegando os arquivos, percebi outra abordagem.

**Comment by luchyanus** [comment]
Freevox é um conjunto de bibliotecas Pascal utilizadas para compilar o
tradutor, ou seja, a síntese de voz do Dosvox. O tradutor foi escrito
em Delphi. A ideia do repositório era colocar um tradutor compilável
em Freepascal. De fato, concluí este trabalho, embora tenha chegado a
bugs que não consegui resolver. Enfim, é possível compilar para Dosvox
em Freepascal, mas não é algo amplamente confiável.

2015-10-12 5:50 GMT-03:00, Alexandre Magno notifications@github.com:

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/magoolation/FreeVox/issues/1

## 

Luciano de Souza

**Comment by alexandre-mbm** [comment]
Eu percebo diretórios para outras coisas no repositório. E o diretório de Pascal, à primeira vista, não me parece ser o que você diz. Ele tem um monte de código de exemplos.

**Comment by luchyanus** [comment]
Oh! É verdade! Já me havia esquecido! São mesmo duas coisas
diferentes! O pacote que mencionei não está aí. A ideia inicialmente
era criar um repositório para que os colegas do grupo Cegos
Programadores colocassem os seus exemplos, manuais, enfim, tudo o que
fosse útil para o compartilhamento.

Em 12/10/15, Alexandre Magnonotifications@github.com escreveu:

> Eu percebo diretórios para outras coisas no repositórios. E o diretório de
> Pascal, à primeira vista, não me parece o que você diz. Ele tem códigos de
> exemplo.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/magoolation/FreeVox/issues/1#issuecomment-147459271

## 

Luciano de Souza

**Comment by alexandre-mbm** [comment]
@luchyanus, não seria o caso de renomear o repositório? Apesar de que talvez o nome atual continue cabendo.

Tenho conversado na lista de e-mails do projeto Linux Acessível, sobre avaliarmos e possivelmente aprendermos acessibilidade de **Git** e **GitHub**. Se você puder comentar a respeito, agradeço. Você por acaso já investigou como Git e GitHub podem ser usados por cegos? E o que descobriu?

Eu estou criando um `git.md` a partir do `git.txt` do @jvesouza. O _pull request_ vem em breve. Estou intercalando essa tarefa com várias outras do meu dia-a-dia. Aquele documento é bem longo e eu tenho estado um pouco cansado, sonolento.

**Comment by alexandre-mbm** [comment]
@luchyanus, há pouco que eu associei o nome à pessoa. Vi no seu endereço de e-mails.

**Comment by luchyanus** [comment]
Se associa àquele sujeito que esteve a movimentar com o Alexandre os
primeiros dias de reativação do grupo Cegos Programadores, então, está
correto. Sou o próprio!

Na verdade, estive cá a perguntar-me. Mas espere um pouco. Será que
não foi o próprio Alexandre a criar o repositório do Freevox? Parece
que a ambos está a faltar um bocadinho de memória!

Em 13/10/15, Alexandre Magnonotifications@github.com escreveu:

> @luchyanus, há pouco que eu associei o nome à pessoa. Vi no seu endereço de
> e-mails.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/magoolation/FreeVox/issues/1#issuecomment-147888416

## 

Luciano de Souza

**Comment by alexandre-mbm** [comment]
@luchyanus, eu não acompanhei os primórdios do grupos cegos-programadores, e não estive no grupo durante os últimos quatro anos. 

Sim, @magoolation é Alexandre Santos Costa, segundo o perfil de GitHub dele.

@luchyanus, seu perfil de GitHub não anuncia seu nome. Acho lhe enviei e-mail há poucas horas.

**Comment by alexandre-mbm** [comment]
Parece que a lista de e-mails cegos-programadores não existe mais...
Não encontro o grupo para reativar minha participação.

**Comment by jvesouza** [comment]
Existe sim, faço parte dela.

On 10/13/2015 09:36 PM, Alexandre Magno wrote:

> Parece que a lista de e-mails cegos-programadores não existe mais...
> Não encontro o grupo para reativar minha participação.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/magoolation/FreeVox/issues/1#issuecomment-147892182.

## 

José Vilmar Estácio de Souza

**Comment by alexandre-mbm** [comment]
> [ lista de e-mails cegos-programadores] Existe sim, faço parte dela.

Qual é o endereço? Não estou achando.

**Comment by jvesouza** [comment]
cegos_programadores@googlegroups.com

Visite o seguinte link para mais detalhes:
http://groups.google.com/group/cegos_programadores?hl=pt-BR

On 10/14/2015 11:51 AM, Alexandre Magno wrote:

> ```
> Existe sim, faço parte dela.
> ```
> 
> Qual é o endereço? Não estou achando.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/magoolation/FreeVox/issues/1#issuecomment-148074114.

## 

José Vilmar Estácio de Souza
